services:
  - type: web
    plan: free
    runtime: node
    name: ably-livesync-neon
    buildCommand: npm install --prod=false; npm run build
    startCommand: npm run start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NEXT_PUBLIC_ABLY_API_KEY
        sync: false
