services:
  - type: web
    name: ably-livesync-neon
    runtime: node
    plan: free
    buildCommand: pnpm install --prod=false; pnpm build
    startCommand: pnpm start
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NEXT_PUBLIC_ABLY_API_KEY
        sync: false
